### ISSUE TITLE
Replace create-react with Nextjs

### ISSUE THREAD

**Issue by krharsh17** [nitpweb/nitp-web-front#1]
Checklist
- [x] Migrate Code
- [x] Update Readme

**Comment by divyaprakash-Rx** [comment]
[Nextjs code uploaded and readme updated](https://github.com/nitpweb/nitp-web-front/commit/2d8e07749093716786de38d5c554c72a9756dbf0)

**Comment by krharsh17** [comment]
Fix the name in the package.json
