### ISSUE TITLE
Fix the footer according to the design

### ISSUE THREAD

**Issue by krharsh17** [nitpweb/nitp-web-front#10]
The  home footer should look like:
![image](https://user-images.githubusercontent.com/46624829/82555070-ba314180-9b84-11ea-924d-5141a552fdb6.png)

Currently, it looks like:
![image](https://user-images.githubusercontent.com/46624829/82555013-9ec63680-9b84-11ea-8a43-b44f77857890.png)

The following specs need to be strictly matched to the design:
- [ ] Line spacings
- [ ] Line heights
- [ ] Font weights
- [ ] Font sizes

Also, please put in all the elements and links that are currently present in the design. And make sure that the entire footer remains responsive across all screen sizes.

**Comment by Severus-Matthew** [comment]
I could do this.
