### ISSUE TITLE
Create the notices-list component

### ISSUE THREAD

**Issue by krharsh17** [nitpweb/nitp-web-front#11]
Here's how it should look finally:
![image](https://user-images.githubusercontent.com/46624829/82571925-4cdfd980-9ba1-11ea-9afc-9e692fa1c8d5.png)

Refer to the figma design for the exact specifications.

Make sure to create
- [ ] List item component for a single notice
- [ ] List component to act as a container for all notices

These components have to be placed inside the `components/home/` directory.

Contact @krharsh17 @divyaprakash-Rx if you face any problems.

**Comment by arsundram** [comment]
This is not an issue, @krharsh17 I suggest you add these things which are not yet started in the TO-DO section under projects.
Who-ever is assigned or who-so-ever takes up that task, can update the status under progress and the task can be tracked easily.
If there is an issue related to it, it can be converted to an issue from there.

Please, move this to the To-do section.
I hope you understand.

**Comment by krharsh17** [comment]
Sure @arsundram sir. However, someone with the right access will have to move this to the to-do section.
