### ISSUE TITLE
Create labels for issues

### ISSUE THREAD

**Issue by krharsh17** [nitpweb/nitp-web-front#5]
@divyaprakash-Rx Please create these labels. Overwrite if any similar label already exists.

| Title  | Description | Colour |
| ---- | ---- | ---- |
| good first issue | Great for newcomers | #7057ff
| difficulty: easy | Beginner-friendly | #fff8ba |
| difficulty: medium| Require prior exprience of working in the repo | #e0e050 |
| difficulty: hard | Requires extensive research and testing | #d32634 |
| type: bug | Something isn't working | #d73a4a |
| type: doc | Improvements or additions to documentation | #0075ca |
| type: enhancement | New feature or request | #a2eeef |
| duplicate | This issue or pull request already exists | #cfd3d7 |
| invalid | This will not be pursued further | #e4e669 |
| postponed | This is stalled for now | #bf0147 |
| help wanted | Extra attention is needed | #008672 |
| question | Needs to be discussed upon | #d876e3 |
| up for grabs | Can be taken up by anyone willing | #c9faff |
| awaiting-triage | Needs to be approved by a maintainer before working | #ed6a53 |

**Comment by rsrajputnitp** [comment]
This should be implemented, bt still i feel it's needed only if we have more no contributors but as of now we have very few ppl fr it.So later on, can pay heed to it for sure
